### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/selenium-router-cli#3]
add unit tests for CLI options

**Comment by jmlavoier** [comment]
I'm up to create some unit tests using Jest. Do you agree?

**Comment by abhijithvijayan** [comment]
@jmlavoier sure why not.

**Comment by jmlavoier** [comment]
@abhijithvijayan Is you cli working? I think the meow config is wront, isn't it? I've created a test folowing a new meow configuration to test the `validation` function. But it can get false positive, that's I'm following the logic that you've created. 

I'm going to create a PR so you can figure out what's going on.

**Comment by abhijithvijayan** [comment]
@jmlavoier The CLI should work if Chrome-driver is properly installed.

I will look into it. Anyway, Thanks for the PR.
